"""
Base agent interface for all specialized agents.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
from langchain_openai import ChatOpenAI
from app.config import get_settings

settings = get_settings()


class BaseAgent(ABC):
    """Base class for all agents in the system."""
    
    def __init__(self, model_name: str = "gpt-4-turbo-preview"):
        """Initialize the agent with an LLM model."""
        self.llm = ChatOpenAI(
            model=model_name,
            temperature=0.7,
            openai_api_key=settings.openai_api_key
        )
        self.agent_name = self.__class__.__name__
    
    @abstractmethod
    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the agent's primary task.
        
        Args:
            input_data: Input data for the agent
            
        Returns:
            Dictionary with agent output and metadata
        """
        pass
    
    def format_output(
        self, 
        content: str, 
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Format agent output in a standardized way.
        
        Args:
            content: Main content generated by the agent
            metadata: Additional metadata about the execution
            
        Returns:
            Formatted output dictionary
        """
        return {
            "agent": self.agent_name,
            "content": content,
            "metadata": metadata or {},
            "success": True
        }
    
    def format_error(self, error: Exception) -> Dict[str, Any]:
        """
        Format error output.
        
        Args:
            error: Exception that occurred
            
        Returns:
            Formatted error dictionary
        """
        return {
            "agent": self.agent_name,
            "error": str(error),
            "success": False
        }
